version: '3.8'

services:
  db:
    image: mysql:8.0.38
    environment:
      MYSQL_ROOT_PASSWORD: 981220Zy+++
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      timeout: 5s
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  go-app:
    build: .
    ports:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    # environment:
      # - REDIS_HOST=redis
      # - REDIS_PORT=6379
      # - MYSQL_HOST=db
      # - MYSQL_PORT=3306
      # - MYSQL_USER=root
      # - MYSQL_PASSWORD=981220Zy+++
      # - MYSQL_DB=db_instagram

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - go-app
